# this file contains the API key for OpenRouter
# it will be used as environment variable in the application

apiVersion: v1
kind: Secret
metadata:
  name: propmptfoo-api-key
  labels:
    app: promptfoo
type: Opaque
data:
  api-key: {{ .Values.openrouterApiKey | b64enc }}



