apiVersion: v1
kind: Service
metadata:
  name: {{ include "promptfoo.fullname" . }}
  labels:
    {{- include "promptfoo.labels" . | nindent 4 }}
#spec:
#  type: {{ .Values.service.type }}
#  ports:
#    - port: {{ .Values.service.port }}
#      targetPort: http
#      protocol: TCP
#      name: http
#  selector:
#    {{- include "promptfoo.selectorLabels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.api_port }}
      targetPort: {{ .Values.service.api_port }}
      protocol: TCP
    - name: web
      port: {{ .Values.service.web_port }}
      targetPort: {{ .Values.service.web_port }}
      protocol: TCP
  selector:
    {{- include "promptfoo.selectorLabels" . | nindent 4 }}